name: sunny
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  intl: ^0.20.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  shared_preferences: ^2.5.3
  bubble_bottom_bar: ^2.0.0
  flutter_local_notifications: ^19.5.0
  path_provider: ^2.1.5
  flutter_native_timezone: ^2.0.0
  flutter_inappwebview: ^6.1.5
  persistent_bottom_nav_bar: ^6.2.1
  avatar_glow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - asset/image/

  fonts:
    - family: NunitoBlack
      fonts:
           - asset: asset/fonts/Nunito/Nunito-Black.ttf
    - family: NunitoBlackItalic
      fonts:
            - asset: asset/fonts/Nunito/Nunito-BlackItalic.ttf
    - family: NunitoBold
      fonts:
            - asset: asset/fonts/Nunito/Nunito-Bold.ttf
    - family: NunitoBoldItalic
      fonts:
            - asset: asset/fonts/Nunito/Nunito-BoldItalic.ttf
    - family: NunitoExtraBold
      fonts:
            - asset: asset/fonts/Nunito/Nunito-ExtraBold.ttf
    - family: NunitoExtraBoldItalic
      fonts:
            - asset: asset/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
    - family: NunitoExtraLight
      fonts:
            - asset: asset/fonts/Nunito/Nunito-ExtraLight.ttf
    - family: NunitoExtraLightItalic
      fonts:
            - asset: asset/fonts/Nunito/Nunito-ExtraLightItalic.ttf
    - family: NunitoItalic
      fonts:
            - asset: asset/fonts/Nunito/Nunito-Italic.ttf
    - family: NunitoLight
      fonts:
            - asset: asset/fonts/Nunito/Nunito-Light.ttf
    - family: NunitoLightItalic
      fonts:
            - asset: asset/fonts/Nunito/Nunito-lightItalic.ttf
    - family: NunitoRegular
      fonts:
            - asset: asset/fonts/Nunito/Nunito-Regular.ttf
    - family: NunitoSemiBold
      fonts:
            - asset: asset/fonts/Nunito/Nunito-Semibold.ttf
    - family: NunitoSemiBoldItalic
      fonts:
            - asset: asset/fonts/Nunito/Nunito-SemiBoldItalic.ttf
